version: 2.1
orbs:
  datadog-agent: datadog/agent@0

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - datadog-agent/setup
      - run: ./gradlew test -Pdd-civisibility
      - datadog-agent/stop
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
  build:
    docker:
      - image: cimg/openjdk:11.0-node
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew assemble
      - setup_remote_docker:
          version: 20.10.7
      - run: |
          GIT_COMMIT_SHA=$(git rev-parse HEAD)
          TAG=0.1.$CIRCLE_BUILD_NUM
          
          npx @datadog/datadog-ci git-metadata upload
          docker build -t yaalexf/ci-integration --build-arg VERSION=${TAG} --build-arg GIT_COMMIT_SHA=${GIT_COMMIT_SHA} .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push yaalexf/ci-integration
workflows:
  spring-boot-app-workflow:
    jobs:
      - test
      - build:
          requires:
            - test
